#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: raylib-flag filname.c"
    exit 1
fi 

filename=$1
output=${filename%.c} #removes .c with % syntex to and leave filename

gcc "$filename" -o "$output" -lraylib -lm -lpthread -ldl -lrt

if [ $? -eq 0 ]; then
    echo "Compiled succesfuly Run with: ./$output"
fi